export const mockData = [
  {
    id: 1,
    title: "김경우는 새로운 도전을 시작했습니다.",
    summary: "이 연구는 미래 기술에 큰 영향을 줄 것입니다.",
    date: new Date(2023, 9, 7),
    comment_count: "13",
    writer: "연구자",
    like_count: "184",
  },
  {
    id: 2,
    title: "김경우는 빅데이터 분석을 진행 중입니다.",
    summary: "최신 알고리즘을 사용하여 분석 중입니다.",
    date: new Date(2022, 4, 25),
    comment_count: "19",
    writer: "분석가",
    like_count: "181",
  },
  {
    id: 3,
    title: "김경우는 머신러닝 프로젝트를 시작했습니다.",
    summary: "이 분석은 중요한 통찰을 제공할 것입니다.",
    date: new Date(2022, 8, 13),
    comment_count: "82",
    writer: "엔지니어",
    like_count: "154",
  },
  {
    id: 4,
    title: "김경우는 UI 디자인을 개선하고 있습니다.",
    summary: "이 프로젝트는 사용자 경험을 혁신할 것입니다.",
    date: new Date(2022, 1, 15),
    comment_count: "51",
    writer: "디자이너",
    like_count: "31",
  },
  {
    id: 5,
    title: "김경우는 AI 모델을 훈련 중입니다.",
    summary: "새로운 데이터셋으로 실험을 진행하고 있습니다.",
    date: new Date(2022, 11, 6),
    comment_count: "98",
    writer: "과학자",
    like_count: "124",
  },
  {
    id: 6,
    title: "김경우는 대규모 프로젝트를 관리하고 있습니다.",
    summary: "이 프로젝트는 높은 가치를 지닙니다.",
    date: new Date(2023, 3, 24),
    comment_count: "35",
    writer: "관리자",
    like_count: "186",
  },
  {
    id: 7,
    title: "김경우는 클라우드 컴퓨팅을 도입했습니다.",
    summary: "클라우드 기술로 혁신을 주도하고 있습니다.",
    date: new Date(2024, 7, 10),
    comment_count: "82",
    writer: "개발자",
    like_count: "168",
  },
  {
    id: 8,
    title: "김경우는 새로운 프로토타입을 개발 중입니다.",
    summary: "이번 프로젝트는 매우 도전적입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "15",
    writer: "설계자",
    like_count: "141",
  },
  {
    id: 9,
    title: "김경우는 인공지능 연구를 심화하고 있습니다.",
    summary: "이 연구는 미래 기술 발전에 중대한 역할을 할 것입니다.",
    date: new Date(2023, 7, 24),
    comment_count: "22",
    writer: "연구원",
    like_count: "65",
  },
  {
    id: 10,
    title: "김경우는 데이터 생성 자동화 시스템을 구축했습니다.",
    summary: "이 시스템은 연구 효율성을 크게 향상시킬 것입니다.",
    date: new Date(2023, 7, 15),
    comment_count: "60",
    writer: "시스템 엔지니어",
    like_count: "62",
  },
  {
    id: 11,
    title: "김경우는 새롭게 출시된 서비스를 홍보 중입니다.",
    summary: "이 서비스는 사용자의 생활을 혁신적으로 바꿀 것입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "86",
    writer: "마케터",
    like_count: "70",
  },
  {
    id: 12,
    title: "김경우는 사용자 피드백을 분석 중입니다.",
    summary: "이 피드백은 향후 개발에 중요한 영향을 미칠 것입니다.",
    date: new Date(2022, 0, 6),
    comment_count: "52",
    writer: "분석가",
    like_count: "157",
  },
  {
    id: 13,
    title: "김경우는 데이터 분석으로 새로운 통찰을 얻고 있습니다.",
    summary: "이 분석은 사업적 성공에 중요한 역할을 할 것입니다.",
    date: new Date(2023, 5, 13),
    comment_count: "18",
    writer: "비즈니스 분석가",
    like_count: "81",
  },
  {
    id: 14,
    title: "김경우는 AI 알고리즘을 최적화하고 있습니다.",
    summary: "이 실험은 성능을 극대화하는데 기여할 것입니다.",
    date: new Date(2023, 5, 24),
    comment_count: "46",
    writer: "AI 엔지니어",
    like_count: "116",
  },
  {
    id: 15,
    title: "김경우는 데이터 기반의 새로운 기회를 탐색 중입니다.",
    summary: "이 프로젝트는 큰 비즈니스 가치를 창출할 것입니다.",
    date: new Date(2023, 4, 27),
    comment_count: "39",
    writer: "사업 개발자",
    like_count: "199",
  },
  {
    id: 16,
    title: "김경우는 빅데이터로 혁신적인 통찰을 얻고 있습니다.",
    summary: "이 연구는 중요한 학술적 기여를 할 것입니다.",
    date: new Date(2023, 1, 26),
    comment_count: "26",
    writer: "학자",
    like_count: "182",
  },
  {
    id: 17,
    title: "김경우는 사용자 인터페이스를 개선하기 위해 연구 중입니다.",
    summary: "이 연구는 사용자의 경험을 크게 향상시킬 것입니다.",
    date: new Date(2023, 1, 17),
    comment_count: "54",
    writer: "인터페이스 전문가",
    like_count: "151",
  },
  {
    id: 18,
    title: "김경우는 새로운 기술을 실험하고 있습니다.",
    summary: "이 실험은 미래의 혁신을 위한 밑거름이 될 것입니다.",
    date: new Date(2022, 9, 28),
    comment_count: "79",
    writer: "실험자",
    like_count: "76",
  },
  {
    id: 19,
    title: "김경우는 AI 기술로 새로운 가능성을 모색 중입니다.",
    summary: "이 실험은 AI 연구에 중대한 영향을 미칠 것입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "35",
    writer: "기술 연구자",
    like_count: "155",
  },
  {
    id: 20,
    title: "김경우는 새로운 데이터 분석 방법을 도입했습니다.",
    summary: "이 프로젝트는 혁신적 도전과제로서 큰 가치를 지닙니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "15",
    writer: "데이터 분석가",
    like_count: "71",
  },
  {
    id: 21,
    title: "김경우는 데이터 분석을 통해 새로운 패턴을 발견했습니다.",
    summary: "이 프로젝트는 향후 연구에 큰 영향을 미칠 것입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "25",
    writer: "분석 전문가",
    like_count: "184",
  },
  {
    id: 22,
    title: "김경우는 사용자 중심의 UI를 개발 중입니다.",
    summary: "이 프로젝트는 사용자 경험을 크게 개선할 것입니다.",
    date: new Date(2023, 6, 12),
    comment_count: "59",
    writer: "UI 디자이너",
    like_count: "40",
  },
  {
    id: 23,
    title: "김경우는 가짜 데이터 생성 도구를 개발하고 있습니다.",
    summary: "이 도구는 데이터 처리 효율성을 크게 향상시킬 것입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "40",
    writer: "도구 개발자",
    like_count: "110",
  },
  {
    id: 24,
    title: "김경우는 자동화된 데이터 생성 기술을 연구 중입니다.",
    summary: "이 기술은 연구 개발에 중요한 기여를 할 것입니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "59",
    writer: "연구 개발자",
    like_count: "193",
  },
  {
    id: 25,
    title: "김경우는 데이터 품질을 향상시키기 위해 노력하고 있습니다.",
    summary: "이 실험은 데이터 분석의 새로운 기준을 제시할 것입니다.",
    date: new Date(2024, 4, 14),
    comment_count: "69",
    writer: "데이터 과학자",
    like_count: "12",
  },
  {
    id: 26,
    title: "김경우는 새로운 인사이트를 발굴 중입니다.",
    summary: "이 연구는 중요한 학문적 기여를 할 것입니다.",
    date: new Date(2023, 0, 26),
    comment_count: "83",
    writer: "학자",
    like_count: "180",
  },
  {
    id: 27,
    title: "김경우는 AI 연구의 새로운 지평을 열고 있습니다.",
    summary: "이 프로젝트는 매우 도전적이며, 큰 가치를 지닙니다.",
    date: new Date(2023, 2, 29),
    comment_count: "49",
    writer: "연구자",
    like_count: "107",
  },
  {
    id: 28,
    title: "김경우는 새로운 기술 트렌드를 연구 중입니다.",
    summary: "이 연구는 업계 전반에 걸쳐 중요한 통찰을 제공합니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "10",
    writer: "기술 분석가",
    like_count: "17",
  },
  {
    id: 29,
    title: "김경우는 미래 기술을 위한 새로운 프로젝트를 시작했습니다.",
    summary: "이 프로젝트는 혁신적이며, 큰 가치를 지닙니다.",
    date: new Date(), // 미래 날짜였던 항목을 현재 날짜로 변경
    comment_count: "64",
    writer: "혁신가",
    like_count: "58",
  },
  {
    id: 30,
    title: "김경우는 UI를 재설계하고 있습니다.",
    summary: "이 재설계는 사용자 경험을 크게 개선할 것입니다.",
    date: new Date(2024, 1, 6),
    comment_count: "5",
    writer: "UI 개발자",
    like_count: "111",
  },
];
